name: bd-sig-action

on:
  workflow_dispatch:  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: mvn
        run: pip install -r requirements.txt
        
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.2.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          blackduck_url: ${{ secrets.BD_URL }}
          blackduck_apiToken: ${{ secrets.BD_TOKEN }}
          blackduck_scan_full: true
